In [1]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, SnowballStemmer,  WordNetLemmatizer
from nltk.tokenize import word_tokenize
import string
import re
import numpy as np
from sklearn.metrics import *

In [2]:


import pandas as pd
df = pd.read_csv('train.csv')


df

essay_id                                          full_text  score
0      000d118  Many people have car where they live. The thin...      3
1      000fe60  I am a scientist at NASA that is discussing th...      3
2      001ab80  People always wish they had the same technolog...      4
3      001bdc0  We all heard about Venus, the planet without a...      4
4      002ba53  Dear, State Senator\r\n\r\nThis is a letter to...      3
...        ...                                                ...    ...
17302  ffd378d  the story " The Challenge of Exploing Venus " ...      2
17303  ffddf1f  Technology has changed a lot of ways that we l...      4
17304  fff016d  If you don't like sitting around all day than ...      2
17305  fffb49b  In "The Challenge of Exporing Venus," the auth...      1
17306  fffed3e  Venus is worthy place to study but dangerous. ...      2

[17307 rows x 3 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17307 entries, 0 to 17306
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   essay_id   17307 non-null  object
 1   full_text  17307 non-null  object
 2   score      17307 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 405.8+ KB


In [4]:
df.describe()

score
count  17307.000000
mean       2.948402
std        1.044899
min        1.000000
25%        2.000000
50%        3.000000
75%        4.000000
max        6.000000

In [5]:
X = df["full_text"]
X

0        Many people have car where they live. The thin...
1        I am a scientist at NASA that is discussing th...
2        People always wish they had the same technolog...
3        We all heard about Venus, the planet without a...
4        Dear, State Senator\r\n\r\nThis is a letter to...
                               ...                        
17302    the story " The Challenge of Exploing Venus " ...
17303    Technology has changed a lot of ways that we l...
17304    If you don't like sitting around all day than ...
17305    In "The Challenge of Exporing Venus," the auth...
17306    Venus is worthy place to study but dangerous. ...
Name: full_text, Length: 17307, dtype: object

In [6]:
y = df["score"]
y

0        3
1        3
2        4
3        4
4        3
        ..
17302    2
17303    4
17304    2
17305    1
17306    2
Name: score, Length: 17307, dtype: int64

In [7]:
# Download NLTK resources
nltk.download('stopwords')
nltk.download('punkt')

# Initialize the PorterStemmer
stemmer =  SnowballStemmer("english")

def preprocess_text(text):
    
    # Tokenize the text into words
    words = word_tokenize(text)
    
    # Remove stop words
    stop_words = set(stopwords.words('english'))
    filtered_words = [word for word in words if word.lower() not in stop_words]
    
    # Apply stemming to each word
    stemmed_words = [stemmer.stem(word) for word in filtered_words]
    
    # Join the stemmed words back into a sentence
    stemmed_text = " ".join(stemmed_words)
    
    return stemmed_text

X = X.apply(preprocess_text)
X


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\keske\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\keske\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


0        mani peopl car live . thing n't know use car a...
1        scientist nasa discuss `` face '' mar . explai...
2        peopl alway wish technolog seen movi , best ne...
3        heard venus , planet without almost oxygen ear...
4        dear , state senat letter argu favor keep elec...
                               ...                        
17302    stori `` challeng explo venus `` inform piec d...
17303    technolog chang lot way live today . nowaday p...
17304    n't like sit around day great opportun partici...
17305    `` challeng expor venus , '' author suggest st...
17306    venus worthi place studi danger . reaosn thei ...
Name: full_text, Length: 17307, dtype: object

In [8]:
X.shape

(17307,)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
vectorizer = CountVectorizer()
#max_df=0.5, analyzer="word", stop_words ="english"

vectors = vectorizer.fit_transform(X).toarray()
vectors.shape


# # Create the TF-IDF vectorizer
# vectorizer = TfidfVectorizer()

# # Fit the vectorizer to the corpus and transform the text data into TF-IDF vectors
# vectors = vectorizer.fit_transform(X).toarray()

# # Print the shape of the TF-IDF vectors
# print(vectors.shape)

(17307, 46335)

In [10]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

vectors_modified = scaler.fit_transform(vectors)



In [11]:
pca = PCA(n_components=100)

X = pca.fit_transform(vectors_modified)

X.shape

(17307, 200)

In [12]:
from sklearn.model_selection import train_test_split, cross_val_score, KFold
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:

X_train.shape

(13845, 200)

In [14]:
X_train

array([[-0.23635006, -1.402425  , -0.13036788, ...,  0.46082268,
         0.76215134,  0.78353253],
       [-0.06891124,  2.04369331, -0.92301373, ..., -0.03789367,
         0.09378988,  0.1904118 ],
       [-0.13053303,  1.34103911, -0.67076681, ...,  0.19340646,
        -0.01206772,  0.08957096],
       ...,
       [-0.15331365,  0.00689215, -0.42528702, ...,  0.58318585,
        -0.67070573,  0.29062397],
       [-0.19620012,  4.07440663, -1.44493857, ...,  0.91498602,
         0.29047327, -0.32709253],
       [-0.16930493,  3.13040824, -1.63557398, ..., -5.80415751,
         1.60517338, -2.88846457]])

In [15]:
X_test.shape

(3462, 200)

In [16]:
X_test

array([[ 0.10163712, -6.95549899,  1.14818393, ..., -1.48870961,
        -0.33515794, -0.311541  ],
       [-0.22672239,  5.1983761 , -1.51934882, ...,  0.05655096,
         0.08995553, -0.6067443 ],
       [-0.16498811,  3.0666007 , -0.93178235, ...,  0.03049506,
         0.06101336, -0.0300396 ],
       ...,
       [-0.14441656,  2.80230954, -1.38969806, ...,  0.24357679,
        -0.17747738,  0.65246938],
       [-0.05784015,  1.86151585, -1.00594522, ..., -0.2059435 ,
         1.03480322,  0.00706999],
       [-0.06761401,  2.38101212, -0.92108956, ...,  0.18638689,
        -0.14723486, -0.17447651]])

In [17]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
import sklearn.metrics as metrics
from xgboost import XGBClassifier

# Initialize models
models = {
    # 'Multinomial Naive Bayes': MultinomialNB(),
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Support Vector Machine': SVC(kernel='linear'),
    'Random Forest Classifier': RandomForestClassifier(),
    'Gradient Boosting Classifier': GradientBoostingClassifier(),
    # 'XGBoost Classifier' : XGBClassifier(),
    'Neural Network': MLPClassifier(max_iter=1000)
}


# Train and evaluate each model
for name, model in models.items():
    print(f"{name} ")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
    print("Accuracy:", accuracy)

    # Calculate precision
    precision = precision_score(y_test, y_pred, average='weighted')
    print("Precision:", precision)

    # Calculate recall
    recall = recall_score(y_test, y_pred, average='weighted')
    print("Recall:", recall)

    # Calculate F1-score
    f1 = f1_score(y_test, y_pred, average='weighted')
    print("F1-score:", f1)

    # Generate confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred)
    print("Confusion matrix:")
    print(conf_matrix)

Logistic Regression 
Accuracy: 0.5473714615829001
Precision: 0.5423070740432601
Recall: 0.5473714615829001
F1-score: 0.5360118166890344
Confusion matrix:
[[ 45 163  45   6   0   1]
 [ 25 615 297  23   1   4]
 [ 18 290 806 139   7   5]
 [  3  19 320 364  36   8]
 [  2   0   8 110  54   9]
 [  0   0   0   5  23  11]]
Support Vector Machine 


In [ ]:
df = pd.DataFrame({'y_true': y_pred, 'y_pred': y_test.to_numpy()})

df 

y_true  y_pred
0          4       3
1          4       3
2          2       3
3          3       3
4          4       4
...      ...     ...
3457       2       1
3458       2       2
3459       3       2
3460       2       2
3461       2       2

[3462 rows x 2 columns]

In [ ]:
# from sklearn.metrics import roc_curve

# n_classes = len(np.unique(y_pred))  # Get number of unique classes

# # Initialize lists to store data for all classes
# fpr_list, tpr_list, auc_scores = [], [], []
# for class_label in range(n_classes):
#   # One-vs-Rest - treat current class as positive, others as negative
#   y_true_ovr = np.where(y_test == class_label, 1, 0)
#   fpr, tpr, _ = metrics.roc_curve(y_true_ovr, y_pred)
#   auc = metrics.roc_auc_score(y_true_ovr, y_pred)
#   fpr_list.append(fpr)
#   tpr_list.append(tpr)
#   auc_scores.append(auc)
#   print(f"AUC Score (Class {class_label}): {auc}")

c:\Users\keske\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_ranking.py:1146: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(


ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

In [ ]:
# from sklearn.model_selection import train_test_split, cross_val_score, KFold
# k = 10
# kf = KFold(n_splits=k, shuffle=True, random_state=42)


# # Initialize models
# models = {
#     # 'Multinomial Naive Bayes': MultinomialNB(),
#     'Logistic Regression': LogisticRegression(max_iter=1000),
#     'Support Vector Machine': SVC(kernel='linear'),
#     'Random Forest Classifier': RandomForestClassifier(),
#     'Gradient Boosting Classifier': GradientBoostingClassifier(),
#     # 'XGBoost Classifier' : XGBClassifier(),
#     'Neural Network': MLPClassifier(max_iter=1000)
# }


# # Train and evaluate each model
# for name, model in models.items():
#     accuracy_scores = cross_val_score(model, X, y, cv=kf, scoring='accuracy')
#     precision_scores = cross_val_score(model, X, y, cv=kf, scoring='precision_weighted')
#     recall_scores = cross_val_score(model, X, y, cv=kf, scoring='recall_weighted')
#     f1_scores = cross_val_score(model, X, y, cv=kf, scoring='f1_weighted')

#     # Print average scores
#     print("Average Accuracy:", np.mean(accuracy_scores))
#     print("Average Precision:", np.mean(precision_scores))
#     print("Average Recall:", np.mean(recall_scores))
#     print("Average F1-score:", np.mean(f1_scores))

Average Accuracy: 0.5689022350006513
Average Precision: 0.5641332287130061
Average Recall: 0.5689022350006513
Average F1-score: 0.5584759794540678
